# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build, Deploy, and Upload Artifacts

on:
  push:
    branches:
      - ''
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('/pom.xml') }}
          restore-keys: 
          
      # Build the project with Maven
      - name: Build with Maven
        run: mvn clean install

      #snapshot deployment prop
        <distributionManagement>
		    	<snapshotRepository>
				    <id>snapshots</id>
			    	<name>a0owv5axnoksm-artifactory-primary-0-snapshots</name>
			    	<url>https://trialwwcxid.jfrog.io/artifactory/hello-world-war-libs-snapshot</url>
		    	</snapshotRepository>
	    	</distributionManagement>
